### ISSUE TITLE
Standalone mode: systemd unit start fails with code 203/EXEC

### ISSUE THREAD

**Issue by tmlmt** [Zuplu/postfix-tlspol#14]
Config file: 

```
server:
  # server:port to listen as a socketmap server
  # or unix:/run/postfix-tlspol/tlspol.sock for Unix Domain Socket
  address: 127.0.0.1:8642

  # set true to enable Postfix 3.10+ TLSRPT support
  # this is experimental, not backwards compatible
  # and may result in delivery failures (default false)
  tlsrpt: true

  # prefetch when TTL is about to expire (default true)
  prefetch: false

dns:
  # must support DNSSEC
  address: 127.0.0.1:53

redis:
  # disable caching (default false)
  disable: true
```

Direct run works: 

```
tmlmt@astro:~/apps/postfix-tlspol$ build/postfix-tlspol -config configs/config.yaml 
postfix-tlspol (c) 2024-2025 Zuplu — v1.6.4-2-ga0e031e
This program is licensed under the MIT License.

Feb 19 00:38:40.430 DEBUG Listening on 127.0.0.1:8642...
```

But the systemd unit fails to start, main process exits with code 203/EXEC.

Systemd unit file: 

```
[Unit]
Description=postfix-tlspol
After=nss-lookup.target network-online.target
Wants=nss-lookup.target

[Service]
WorkingDirectory=/home/tmlmt/apps/postfix-tlspol
ExecStart=/home/tmlmt/apps/postfix-tlspol/build/postfix-tlspol -config /home/tmlmt/apps/postfix-tlspol/configs/config.yaml
ExecReload=/bin/kill -HUP $MAINPID
DynamicUser=yes
Restart=always
RestartSec=5
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
LockPersonality=yes
PrivateUsers=yes
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectClock=yes
ProtectSystem=strict
ProtectHostname=yes
ProtectProc=invisible
ProcSubset=pid
RestrictRealtime=yes
RestrictNamespaces=yes
RestrictSUIDSGID=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RemoveIPC=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
SystemCallErrorNumber=EPERM
CapabilityBoundingSet=
ReadOnlyPaths=/home/tmlmt/apps/postfix-tlspol
UMask=0111
RuntimeDirectory=postfix-tlspol
RuntimeDirectoryMode=1777
BindPaths=/run/postfix-tlspol

[Install]
WantedBy=multi-user.target
```

Running on Ubuntu 24.04.1, built successfully with Go 1.24

Could you help out?
