### ISSUE TITLE
move unbound and valkey into their own containers

### ISSUE THREAD

**Issue by jahlives** [Zuplu/postfix-tlspol#24]
@DragonWork 

imho one thing that should be changed :-) Move the services into their own containers. This is more the docker approach: one service one container. That way you would not have to perform "stunts" in the tlspol Dockerfile to get the logs ;-) Wrote this docker-compose file
```yaml
services:
  postfix-tlspol:
    image: zuplu/postfix-tlspol
    container_name: postfix-tlspol
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    ports:
      - "8642:8642"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - postfix-tlspol-data:/data
    depends_on:
      unbound-tlspol:
        condition: service_healthy
  valkey-tlspol:
    image: valkey/valkey:8.1-alpine3.21
    container_name: valkey-tlspol
    restart: unless-stopped
    volumes:
      - ./docker-entrypoint-valkey.sh:/usr/local/bin/entrypoint.sh:ro
    networks:
      - internal
  unbound-tlspol:
    image: mvance/unbound:1.21.1
    container_name: unbound-tlspol
    restart: unless-stopped
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      - internal
    depends_on:
      - valkey-tlspol
volumes:
  postfix-tlspol-data:

networks:
  internal:
```
for tlspol I use this Dockerfile
```Dockerfile
FROM golang:1.24.0-alpine3.21@sha256:2d40d4fc278dad38be0777d5e2a88a2c6dee51b0b29c97a764fc6c6a11ca893c AS workspace

ARG TARGETPLATFORM
ARG GITHUB_ACTIONS

# Create a non-root user
RUN addgroup -g 1000 default \
  && adduser -G default -u 1000 default -D

RUN apk add --no-cache git

# Copy postfix-tlspol
COPY . /build

# Build postfix-tlspol
RUN /build/scripts/build.sh build-only

# Remove residual toolchain
RUN go clean -cache -modcache \
  && rm -rf /build \
  && rm -rf /usr/local/go \
  && rm -rf /go \
  && rm -rf /home \
  && apk --purge del git apk-tools

# Create data dir
RUN mkdir -p /data \
  && chown default:default /data

# Setup postfix-tlspol
RUN sed -i -e "s/127\.0\.0\.1:8642/0\.0\.0\.0:8642/" -e "s/127\.0\.0\.53:53/unbound-tlspol:53/" -e "s/127\.0\.0\.1:6379/valkey-tlspol:6379/" /etc/postfix-tlspol/config.yaml \
  && chown -R default:default /etc/postfix-tlspol

# Setup entrypoint
RUN <<EOR
  cat <<EOF > /entrypoint.sh
#!/bin/sh
set -e
# Upgrade from old container with persistent config.yaml
if [ -e /data/config.yaml ]; then
  mv /data/config.yaml /data/config.yaml.bak
  echo "WARNING: /data/config.yaml is deprecated and removed. See /etc/postfix-tlspol/config.yaml (which will be overriden on each update as it is maintained by the container)"
fi
exec /usr/bin/postfix-tlspol -config /etc/postfix-tlspol/config.yaml
EOF
  chmod +x /entrypoint.sh
EOR

# Squash layers
FROM alpine:3.21 AS final
COPY --from=workspace /usr/bin/postfix-tlspol /usr/bin/postfix-tlspol
COPY --from=workspace /etc/postfix-tlspol/config.yaml /etc/postfix-tlspol/config.yaml
COPY --from=workspace /entrypoint.sh /entrypoint.sh
RUN addgroup -g 1000 default \
  && adduser -G default -u 1000 default -D \
  && chown default:default /entrypoint.sh \
  && chmod 0500 /entrypoint.sh


USER default

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/entrypoint.sh"]

EXPOSE 8642
```
replaced the hostnames for unbound and valkey with their docker service names. Also changing ENTRYPOINT and adding CMD helps as that way one can `docker run -it --rm TLSPOL sh` and start a container to check the configs inside without always executing tlspol. Hopefully sysadmins will say thank you :-)

this as `docker-entrypoint-valkey.sh`
```sh
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
# or first arg is `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
        set -- valkey-server "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'valkey-server' -a "$(id -u)" = '0' ]; then
        find . \! -user valkey -exec chown valkey '{}' +
        exec setpriv --reuid=valkey --regid=valkey --clear-groups -- "$0" "$@"
fi

# set an appropriate umask (if one isn't set already)
um="$(umask)"
if [ "$um" = '0022' ]; then
        umask 0077
fi

exec "$@" $VALKEY_EXTRA_FLAGS
```
and the `unbound.conf` (I took you config from Dockerfile and adjusted it a bit aka no daemon and no logfile as services in docker should just log to stdout)
```yaml
server:
  username: _unbound
  chroot: ""
  do-daemonize: no
  use-syslog: no
  verbosity: 1
  access-control: 0.0.0.0/0 allow
  log-servfail: yes
  log-queries: yes
  ede: yes
  interface: 0.0.0.0
  port: 53
  do-ip4: yes
  prefer-ip4: yes
  do-ip6: yes
  prefer-ip6: no
  do-udp: yes
  do-tcp: yes
  max-udp-size: 1232
  edns-buffer-size: 1232
  auto-trust-anchor-file: "var/root.key"
  cache-min-ttl: 10
  cache-max-ttl: 240
  serve-original-ttl: yes
  serve-expired: no
  prefetch-key: yes
  prefetch: yes
  hide-identity: yes
  hide-version: yes
  target-fetch-policy: "4 3 2 2 1"
  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-algo-downgrade: yes
  harden-below-nxdomain: no
  harden-referral-path: no
  harden-large-queries: no
  harden-short-bufsize: yes
  harden-unknown-additional: no
  aggressive-nsec: no
  val-permissive-mode: no
  unknown-server-time-limit: 1500
  jostle-timeout: 1000
  discard-timeout: 4000
  so-reuseport: yes
  num-threads: 2
  qname-minimisation: no
  minimal-responses: yes
  infra-cache-min-rtt: 4500
  infra-keep-probing: yes
  module-config: "validator iterator"
remote-control:
  control-enable: no
```
I really thing services in docker should be capsuled into their own containers. With compose you can make them able to reach each other via the docker service name. Also you can easy get the logs of one service by `docker compose logs -t -f unbound-tlspol` or get them all by `docker compose logs -t -f`
